spring:
  application:
      name: user-service
  kafka:
    topic:
      name: ${KAFKATOPICNAME}
      group: ${KAFKATOPICGROUP:user-service}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        sasl:
          mechanism: ${KAFKASASLMECHANISM:PLAIN}
          jaas:
            config: ${KAFKASASLJAASCONFIG}
        spring:
          json:
            type:
              mapping: userprofile:com.microsoft.gbb.miyagi.orderservice.entity.UserProfile
      bootstrap-servers: ${KAFKABOOTSTRAPSERVERS:localhost:9092}
    security:
      protocol: ${KAFKASECURITYPROTOCOL:PLAINTEXT}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
  config:
    import: optional:classpath:.env[.properties]
  jms:
    servicebus:
      connection-string: ${SERVICEBUSCONNECTIONSTRING}
      pricing-tier: ${SERVICEBUSPRICINGTIER:Basic}
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQLPASSWORD}
    username: ${MYSQLUSER}
    url: ${MYSQLURL}
  flyway:
    baseline-on-migrate: 'true'
  banner:
    location: static/banner.txt
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false
springdoc:
  swagger-ui:
    enabled: 'true'
    path: /swagger
  api-docs:
    path: /api-docs
topic:
  name:
    producer: ${KAFKATOPICNAME}
server:
  port: '8901'
